# Site configuration

title: Sud Web
tagline: les 25 et 26 mai 2018 à Anduze
description: Deux journées pour faire le plein d'inspiration entre super-héros du web.
logo: /assets/images/twittercard.png
url: https://sudweb.fr
repository: sudweb/2018
baseurl: /2018
locale: fr_FR

## SEO

robots: index,follow
twitter:
  username: SudWeb
image:
  path: /assets/images/twittercard.png
  height: 200
  width: 200
social:
  type: organization
  links:
    - https://twitter.com/SudWeb
    - https://www.facebook.com/SudWeb
facebook:
  publisher: https://www.facebook.com/SudWeb/

github:
  url: https://sudweb.fr/2018

# Services configuration

analytics:
  google :
    tracking_id : "UA-22076213-1"

weezevent:
    mini-site-url: https://www.weezevent.com/sudweb-2018

newsletter:
  url: http://sudweb.us2.list-manage.com/subscribe?u=af19b58cf514c01eca3f7652e&id=b579f5b507

# Jekyll configuration

permalink: /:title/
paginate: 5
timezone: Europe/Paris
sass:
    sass_dir: _sass
    style: compressed

# collections:
#   talks:
#     output: false
#     order: date asc
#     permalink: /talks/:path/
#     sitemap: false
#   components:
#     output: false
#   colors:
#     output: false

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      locale: fr_FR
      layout: default
      is_home: false
      image:
        path: /assets/images/twittercard.png?date=20180106
        width: 560
        height: 300
  -
    scope:
      path: "en"
      type: pages
    values:
      baseurl: "/2018/en"
      locale: en_US
      layout: default
      image:
        path: /assets/images/twittercard-en.png?date=20180107
        width: 560
        height: 300

include:
  - _headers

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - octopress-autoprefixer
