# Site configuration

title: We Love Speed
seo_title: We Love Speed
tagline:
  2018: "9 octobre 2018, Bordeaux"
  2019: "20 septembre 2019, Lille"
description: "L’événement français des mordus de web performance !"
description_en: "The French event for web performance enthusiasts"
logo: /assets/images/twittercard.png
url: https://www.welovespeed.com
domain: 'welovespeed.com'
mail: contact@welovespeed.com
main_color: cd2f2b
social:
  twitter: "_welovespeed"
repository: welovespeed/welovespeed.com
baseurl: ""
destination: _site/
locale: fr_FR
logo: https://welovespeed.com/assets/images/social/logo.jpg
lazyload:
  placeholder: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="

# Est-ce qu'on vend des places à tarif plein, est-ce qu'on propose une liste d'attente ou les deux ?
current_edition: 2019
sponsoring:
  fr_FR: '/assets/docs/2019/sponsoring_fr.pdf'
tickets:
  selling: false
  waiting-list: false
  price: "180"
  price_currency: "EUR"
infos:
  display: false
  video: true

# Compression du code HTML en production
compress_html:
  ignore:
    envs:
      - 'development'

## SEO

robots: index,follow

# Services configuration

weezevent:
    mini-site-url: https://www.weezevent.com/welovespeed-2018

newsletter:
  display: true
  url: "https://welovespeed.us18.list-manage.com/subscribe/post?u=871757160e8496642288193e3&amp;id=1695ce944b"
  honeypot: "b_871757160e8496642288193e3_1695ce944b"

# Jekyll configuration

timezone: Europe/Paris
sass:
    sass_dir: _sass
    style: compressed

cloudinary:
  cloud_name: we-love-speed
  origin_url: "https://welovespeed.netlify.com"
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
    gold_sponsors:
      min_width: 60
      max_width: 1760
      fallback_max_width: 880
      steps: 3
      sizes: "100px"
    avatar:
      min_width: 60
      max_width: 110
      fallback_max_width: 220
      steps: 2
      sizes: "110px"

permalink: "/blog/:year-:month-:day-:slug/"

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
  talks:
    output: false
    order: date asc
    permalink: /talks/:path/
    sitemap: false

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
  -
    scope:
      path: "pages/en"
      type: pages
    values:
      baseurl: "/en"
      locale: en_US
  -
    scope:
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "pages/fr/2018"
    values:
      year: 2018
  -
    scope:
      path: "pages/en/2018"
    values:
      year: 2018
  -
    scope:
      path: "pages/fr/2019"
    values:
      year: 2019
  -
    scope:
      path: "pages/en/2019"
    values:
      year: 2019
  -
    scope:
      path: "_talks/2018"
    values:
      year: 2018
  -
    scope:
      path: "_talks/2019"
    values:
      year: 2019

microtypo:
  median: true

include:
  - _headers
  - _redirects

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script
  - "Rakefile"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
